### PR TITLE
Refactor examples and interfaces

### PR DESCRIPTION
**Pull request by wjwwood**
I know the diff is hard to read in some places, but please just look at the resulting files as they are. I think it will be easiest to review it that way.

@esteve I also modified the services and parameters examples to be as concise as possible, I hope you don't mind. We can iterate on them if you like to make sure the API's are sufficiently represented. For instance, we might want to create additional parameter examples since I dropped the part of the example dealing with parameter events, since it was at the end and would never really print anything. It might even make sense to have an example just for listing parameters.

This also depends on https://github.com/ros2/rclcpp/pull/42.

Connects to ros2/examples#4

### CODE REVIEW

**Comment by wjwwood** [comment]
@esteve I just pushed another commit that adds additional parameter examples to make up for the content I removed from the original pair.

**Comment by dirk-thomas** [comment]
Does the `rclc_examples` not work anymore?

**Comment by dirk-thomas** [comment]
Does the `ros1_like` Python code has enough value to keep it?

**Comment by wjwwood** [comment]
> Does the rclc_examples not work anymore?

Before they were just source files; They weren't even listed in the `CMakeLists.txt`. But I will give the a try and fix the build if it is straight forward. I honestly don't remember what the issue was at this point.

> Does the ros1_like Python code has enough value to keep it?

I could create a disabled package like `rclc_examples` which holds them. I figured we could go back and get those examples when we needed them using the tag I created. What would everyone prefer?

**Comment by esteve** [comment]
@wjwwood of course I don't mind, they look much better now! :-) Thanks for taking the time to make them more readable and concise.

+1

**Comment by wjwwood** [comment]
I fixed up the `rclc_examples` in 640d426, but they still don't link because there are pieces of `rclc` which are not implemented yet. It's basically just an API, which is sufficient to build an example on, but won't link and run. So I left the `AMENT_IGNORE` for now.

**Comment by wjwwood** [comment]
I still need to test out the new examples, to make sure they work as expected, I'm doing that now.

**Comment by wjwwood** [comment]
Ok, the pub/sub and service examples work. There are some issues with the parameter examples, which @esteve and I looked at for a while today, but I think they'll take some more work to figure out and the issues are with the rclcpp implementation (not caused by the demo). So I'd like to go ahead and merge this refactoring without fixing them for now.

**Pull request merged**
