### PR TITLE
Pass request header to callbacks

### PR DESCRIPTION
**Pull request by esteve**
Connects to ros2/rclcpp#21

### CODE REVIEW

**Comment by esteve** [comment]
@dirk-thomas @tfoote @wjwwood

**Comment by wjwwood** [comment]
We don't have to do this now, but in the future it would be nice to make this signature optional. While we should make the header available to those who want it, most people don't care about it and only want the request and response.

**Comment by wjwwood** [comment]
Otherwise, +1

**Comment by esteve** [comment]
@wjwwood I just added support for both types of callbacks (with and without request headers).

**Comment by esteve** [comment]
@wjwwood https://github.com/ros2/rclcpp/commit/8abae8ac829946620c9defd983e1f947839b041a

**Comment by dirk-thomas** [comment]
With #13 being merged please also update the test to match the new API. Also consider using the new `spin_until` functions as commented in https://github.com/ros2/examples/pull/13#discussion_r28722152

**Comment by dirk-thomas** [comment]
+1

**Comment by esteve** [comment]
@dirk-thomas the PR where the `spin_*` functions are implemented is not yet merged because the PR is not reviewed yet :wink:

**Comment by tfoote** [comment]
+1

**Pull request merged**
