### PR TITLE
example of method chaining for object pool bounds struct

### PR DESCRIPTION
**Pull request by jacquelinekay**
requires ros2/rclcpp/pull/82

### CODE REVIEW

**Comment by dirk-thomas** [comment]
+1

**Comment by wjwwood** [comment]
+1

Did you run uncrustify over this? I find the line wrapping of the chained methods strange looking, but I don't know what else you might do.

**Comment by jacquelinekay** [comment]
Yep, I tried indenting four spaces on the second line and uncrustify
corrected it.

**Comment by jacquelinekay** [comment]
I got uncrustify to accept an indented second line. I think it looks better now.

**Pull request merged**
