### PR TITLE
Add test linting to wait_set and fix issues.

### PR DESCRIPTION
**Pull request by athackst**
Found this issue when trying to add humble (seen in) athackst/vscode_ros2_workspace#29

### CODE REVIEW

**Review by clalancette — CHANGES_REQUESTED** [review]
For this to work properly, you'll also need to add:

```
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
```

to the package.xml.  Once that is in place, and CI passes, this looks good to me.

**Comment by athackst** [comment]
Done!

**Review by clalancette — APPROVED** [review]
Thanks for iterating.  Looks good to me.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17011/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/11572/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/17427/)

**Comment by clalancette** [comment]
@Mergifyio backport rolling

**Pull request merged**
