### PR TITLE
[dashing_backport] make member function const (#247)

### PR DESCRIPTION
**Pull request by Karsten1987**
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The definition is in a `.cpp` file only. So it is not part of the public API / ABI - no external package can rely on it.

**Comment by jacobperron** [comment]
> The definition is in a .cpp file only. So it is not part of the public API / ABI - no external package can rely on it.

Missed that. Thanks. :upside_down_face:

**Comment by jacobperron** [comment]
I expect CI will depend on https://github.com/ros2/rclcpp/pull/796

**Comment by jacobperron** [comment]
I included this PR as part of the CI job for https://github.com/ros2/rclcpp/pull/796#issuecomment-516059028.

**Pull request merged**
