### PR TITLE
Clean up allocator for gcc 5.3

### PR DESCRIPTION
**Pull request by jacquelinekay**
Connects to #107 

**Do not merge until we update to Xenial; this will break the build with the default gcc on Trusty.**

### CODE REVIEW

**Comment by jacquelinekay** [comment]
[Build Status](http://ci.ros2.org/job/ci_linux/1411/)

**Comment by dirk-thomas** [comment]
Should the branch name be changed to `xenial` so that the patch can be tested together with all the other changes?

**Comment by dirk-thomas** [comment]
I also deleted the xenial branch.

**Comment by jacquelinekay** [comment]
Thanks.

**Pull request merged**
