### PR TITLE
fix ambiguous overloaded function call on Windows

### PR DESCRIPTION
**Pull request by wjwwood**
Connects to ros2/rmw_connext#26

### CODE REVIEW

**Comment by wjwwood** [comment]
This is basically the patch @esteve proposed, I could not find a way to make it work without this... I tried `explicit` on the constructors and I tried using `auto` to store the function before passing it in, but neither of those worked.

**Comment by wjwwood** [comment]
For review.

**Comment by dirk-thomas** [comment]
Is a similar change also necessary for the tests?

**Comment by tfoote** [comment]
lgtm

**Comment by esteve** [comment]
+1, I have an idea of using std::enable_if and std::is_convertible, but I rather get this merged now and see if we can improve it later.

**Comment by wjwwood** [comment]
Sounds good to me, Thanks.

**Comment by wjwwood** [comment]
I created an issue to track it: https://github.com/ros2/examples/issues/20

**Pull request merged**
