### PR TITLE
Replace deprecated spin_until_future_complete

### PR DESCRIPTION
**Pull request by hliberacki**
Replace deprecated spin_until_future_complete with spin_until_complete

Signed-off-by: Hubert Liberacki <hliberacki@gmail.com>

### CODE REVIEW

**Comment by hliberacki** [comment]
Due to change in RCLCPP - https://github.com/ros2/rclcpp/pull/1874 Pull request

**Review by fujitatomoya — CHANGES_REQUESTED** [review]
we should avoid unnecessary changes which are irrelevant to this PR.

**Comment by hliberacki** [comment]
https://github.com/ros2/rclcpp/pull/1874#issuecomment-1086906375 Passing CI with all related PRs linked and build together.

**Review by fujitatomoya — APPROVED** [review]

**Review by SteveMacenski — APPROVED** [review]

**Comment by christophebedard** [comment]
I've opened #376 to replace this PR.

**Comment by christophebedard** [comment]
This can be closed, see https://github.com/ros2/examples/pull/376#issuecomment-2035715538

**Pull request closed without merging**
