### PR TITLE
(fix) rename listener and talker with suffix _c

### PR DESCRIPTION
**Pull request by Karsten1987**
addresses https://github.com/ros2/examples/issues/125

### CODE REVIEW

**Comment by dirk-thomas** [comment]
A CI build doesn't make sense since the package folder has an `AMENT_IGNORE` file. Did you build it locally? If yes, this looks good to me.

**Comment by Karsten1987** [comment]
the rclc examples don't have much value right now since there is no real client library for c yet.

**Comment by mikaelarguedas** [comment]
it doesn't compile locally because it's using outdated TYPESUPPORT macros and rely on code that doesn't exist (rclc is a dummy package with only header definition and no actual functions and no target created). So we may want to postpone this until there is an actual implementation of rclc

**Comment by dirk-thomas** [comment]
While the package isn't "ready" yet I still think the proposed patch makes sense. I would be in favor of merging it.

**Comment by Karsten1987** [comment]
we should then iterate over the complete cmake file and verify their dependencies.

**Comment by Karsten1987** [comment]
I'll merge this due to its consistency with other client libraries. https://github.com/ros2/examples/blob/master/rclcpp_examples/CMakeLists.txt

We iterate over this once rclc is actually having example code.

**Pull request merged**
