### PR TITLE
Include feedback from https://github.com/ros2/ros2/issues/46

### PR DESCRIPTION
**Pull request by esteve**
Fixes to get this compiling after ros2/rcl_interfaces#4

Connects to ros2/ros2#46

@dirk-thomas @jacquelinekay @tfoote @wjwwood please review

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Can you please trigger one CI run for these branches.

**Comment by wjwwood** [comment]
+1

**Comment by esteve** [comment]
Linux buildfarm:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_linux/146/

**Comment by esteve** [comment]
Mac OSX:

http://54.183.26.131:8080/view/ros2/job/ros2_batch_ci_osx/157/

**Comment by esteve** [comment]
Linux build passes. Mac OSX builds fine, but tests fail.

**Comment by dirk-thomas** [comment]
+1

**Pull request merged**
